feat: init device with optional serial, port, mjpeg port
electricbubble/gwda pull request #14
Opened 2022-08-23 11:55 UTC by debugtalk

2022-08-23 14:43 UTC, electricbubble requested changes
有一点小细节，可以考虑改一下

2022-08-23 14:43 UTC, electricbubble commented on device.go
> +	return nil, fmt.Errorf("device %s not found", device.serialNumber)
既然上面选择使用 [github.com/pkg/errors](https://pkg.go.dev/github.com/pkg/errors),

那这里也索性使用 [errors.Errorf](https://pkg.go.dev/github.com/pkg/errors#Errorf),

---

但从我个人角度考虑，这个场景下没必要使用 [github.com/pkg/errors](https://pkg.go.dev/github.com/pkg/errors),

`fmt.Errorf` 就足够了

2022-08-23 14:43 UTC, electricbubble commented on device.go
> +type DeviceOptions func(d *Device)
我个人倾向于使用 `DeviceOption` 
> 单数，每一个 `func WithXXX` 都是一个选项

2022-08-24 02:09 UTC, debugtalk commented on device.go
> +type DeviceOptions func(d *Device)
👍 已修改

2022-08-24 02:14 UTC, debugtalk commented on device.go
> +	return nil, fmt.Errorf("device %s not found", device.serialNumber)
好的，我改为 fmt.Errorf 了

2022-08-24 02:19 UTC, merged